stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/web:2.3.0
      pushRemote: true
      registry: index.docker.io
timeout: 60
