stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/web:2.1.2
      pushRemote: true
      registry: index.docker.io
timeout: 60
