apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
    field.cattle.io/creatorId: user-rddjj
    field.cattle.io/publicEndpoints: '[{"addresses":["51.68.226.235"],"port":443,"protocol":"HTTPS","serviceName":"bf:ingress-196204fb02933559adcb7a3ac1f5f686","ingressName":"bf:front","hostname":"blueforest.org","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"DaemonSet","metadata":{"annotations":{"deprecated.daemonset.template.generation":"1","field.cattle.io/creatorId":"user-rddjj","field.cattle.io/publicEndpoints":"[{\"addresses\":[\"51.68.226.235\"],\"port\":443,\"protocol\":\"HTTPS\",\"serviceName\":\"bf:ingress-196204fb02933559adcb7a3ac1f5f686\",\"ingressName\":\"bf:front\",\"hostname\":\"blueforest.org\",\"allNodes\":true}]"},"creationTimestamp":"2018-10-30T17:28:09Z","generation":1,"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"daemonSet-bf-web"},"name":"web","namespace":"bf","resourceVersion":"1502446","selfLink":"/apis/apps/v1beta2/namespaces/bf/daemonsets/web","uid":"2ba80e8b-dc69-11e8-8d8e-fa163e68c03b"},"spec":{"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"daemonSet-bf-web"}},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2018-10-30T17:28:09Z"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"daemonSet-bf-web"}},"spec":{"containers":[{"env":[{"name":"NODE_ENV","value":"production"}],"image":"blueforest/web:1.4.3","imagePullPolicy":"Always","name":"web","resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"blueforest"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":1},"type":"RollingUpdate"}}}
  creationTimestamp: 2018-10-30T17:28:09Z
  generation: 2
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-web
  name: web
  namespace: bf
  resourceVersion: "1643673"
  selfLink: /apis/apps/v1beta2/namespaces/bf/daemonsets/web
  uid: 2ba80e8b-dc69-11e8-8d8e-fa163e68c03b
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-web
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2018-10-30T17:28:09Z
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-web
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        image: blueforest/web:1.4.5
        imagePullPolicy: Always
        name: web
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: blueforest
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate